DROP TABLE WHITE;
CREATE TABLE WHITE (
	NO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000),
	POSTDATE DATE
);

DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '어제의 아침', '짜장밥', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '어제의 점심', '우동', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '어제의 저녁', '콩나물국', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '오늘의 아침', '치킨너겟', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '오늘의 점심', '콩나물국', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '오늘의 저녁', '핫도그', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '내일의 아침', '미역국', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '내일의 점심', '햄버거', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '내일의 저녁', '소야볶음', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '모레의 아침', '카레', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '모레의 점심', '불닭볶음면', SYSDATE);
INSERT INTO WHITE VALUES(NO_SEQ.NEXTVAL, '모레의 저녁', '야채스프', SYSDATE);

SELECT * FROM WHITE;

-- HR 계정 살리기 (Lock풀고 비밀번호 1111)
ALTER USER HR ACCOUNT UNLOCK;
ALTER USER HR IDENTIFIED BY 1111;

-- HR 계정의 EMPLOYEES 테이블(HR.EMPLOYEES)을 복사하여
-- 현재 계정에 EMP 테이블을 생성하시오. | 다른계정.다른테이블
CREATE TABLE EMP AS SELECT * FROM HR.EMPLOYEES;

SELECT * FROM EMP;

DESC EMP;
