DROP TABLE WHITE;
CREATE TABLE WHITE (
	NO NUMBER PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000),
	POSTDATE DATE
);

DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;