DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE PROFESSOR;
DROP TABLE COURSE;
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

DROP TABLE SCHEDULE;
DROP TABLE PLAYER;
DROP TABLE NATION;
DROP TABLE MEMBERS;
DROP TABLE EVENT;