DROP TABLE CUSTOMER;
DROP TABLE BANK;

CREATE TABLE BANK(
BANK_CODE VARCHAR2(20) CONSTRAINT BANK_PK PRIMARY KEY,
BANK_NAME VARCHAR2(30));

CREATE TABLE CUSTOMER(
NO NUMBER CONSTRAINT CUSTOMER_PK PRIMARY KEY,
NAME VARCHAR2(30) CONSTRAINT NAME_NN NOT NULL,
PHONE VARCHAR2(30) CONSTRAINT PHONE_UQ UNIQUE,
AGE NUMBER CONSTRAINT AGE_CK CHECK (AGE BETWEEN 0 AND 100),
BANK_CODE VARCHAR2(20) CONSTRAINT CUSTOMER_BANK_FK REFERENCES BANK (BANK_CODE));