DROP TABLE BLUE;
CREATE TABLE BLUE
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100),
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000),
	POSTDATE DATE
);

DROP SEQUENCE BLUE_SEQ;
CREATE SEQUENCE BLUE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;