DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NO NUMBER PRIMARY KEY,
	ID VARCHAR2(50),
	NAME VARCHAR2(100),
	GENDER VARCHAR2(10),
	ADDRESS VARCHAR2(200)
);
