DROP SEQUENCE ARTIST_SEQ;
CREATE SEQUENCE ARTIST_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE ARTIST;
CREATE TABLE ARTIST
( 
	ANO NUMBER PRIMARY KEY, 
	MNO NUMBER REFERENCES MEMBER(MNO),  
 	ANAME VARCHAR2(50), 
	ACOMMENT VARCHAR2(200), 
 	AIMAGE VARCHAR2(100),
 	BIMAGE VARCHAR2(100)
);

INSERT INTO ARTIST VALUES(ARTIST_SEQ.NEXTVAL, 7, '아티스트공방', '저희 아티스트 공방은 20년 간의 노하우를 바탕으로 고객님의 요구를 100% 만족시키기 위해 지금도 노력하고 있습니다.', NULL);
SELECT * FROM ARTIST;

CREATE OR REPLACE VIEW A_VIEW AS
SELECT ROWNUM RN, E.*
    FROM(SELECT D.*, C
        FROM(SELECT A.ANO, COUNT(*) C
            FROM (SELECT T.ANO, P.PNO
                FROM ARTIST T, PRODUCT P
                WHERE T.ANO = P.ANO          
            ) A, ORDERS O
            WHERE A.PNO = O.PNO
            GROUP BY A.ANO) B, ARTIST D
        WHERE B.ANO = D.ANO
        ORDER BY C DESC) E;
		
	
		
		
		