DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE CART;
CREATE TABLE CART
(
	CNO NUMBER PRIMARY KEY, 
	MNO NUMBER REFERENCES MEMBER (MNO), 
	PNO NUMBER REFERENCES PRODUCT (PNO), 
	SNO NUMBER REFERENCES STOCK (SNO),
	CAMOUNT NUMBER, 
	COPTION VARCHAR2(100)
);

SELECT * FROM MEMBER;
SELECT * FROM ARTIST;
SELECT * FROM PRODUCT;
SELECT * FROM STOCK;
SELECT * FROM CART;

SELECT A.MNO, A.PNO, A.COPTION, SUM(A.CAMOUNT)
FROM(SELECT C.*
	FROM MEMBER M, CART C
	WHERE M.MNO = C.MNO) A
GROUP BY A.MNO, A.COPTION, A.PNO;

UPDATE MEMBER
 SET MPW = 'rlaqja12!@'
WHERE MNO = 8;