DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	MNO NUMBER PRIMARY KEY,
	MSNO VARCHAR2(10),
	MNAME VARCHAR2(50) NOT NULL,
	MEMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MPW	VARCHAR2(50) NOT NULL,
	MGENDER	VARCHAR2(10),
	MPNO VARCHAR2(50),
	MADDR VARCHAR2(100),
	MLASTADDR VARCHAR2(100),
	MPHONE	VARCHAR2(50),
	MPFILENAME VARCHAR2(300),
	MPAYMENT VARCHAR2(50),
	MPOINT	NUMBER,
	MGRADE	VARCHAR2(10),
	MREGDATE DATE
);

INSERT 
INTO MEMBER
(MNO, MNAME, MEMAIL, MPW, MREGDATE)
values (MEMBER_SEQ.NEXTVAL, 'admin', 'admin@classick.com', '1111', SYSDATE); 

INSERT 
INTO MEMBER
(MNO, MNAME, MEMAIL, MPW, MREGDATE)
values (MEMBER_SEQ.NEXTVAL, 'artist', 'artist@classick.com', '1111', SYSDATE); 

INSERT 
INTO MEMBER
(MNO, MNAME, MEMAIL, MPW, MREGDATE)
values (MEMBER_SEQ.NEXTVAL, 'member', 'member@classick.com', '**user1**', SYSDATE);

SELECT * FROM MEMBER;

