DROP SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE ORDERS;
CREATE TABLE ORDERS
(
	ONO NUMBER PRIMARY KEY, 
	MNO NUMBER REFERENCES MEMBER (MNO), 
	PNO NUMBER REFERENCES PRODUCT (PNO), 
	OAMOUNT NUMBER NOT NULL, 
	ODATE DATE, 
	OADDR VARCHAR2(100) NOT NULL, 
	OPHONE VARCHAR2(20) NOT NULL, 
	OPAYMENT VARCHAR2(50), 
	OOPTION VARCHAR2(1000), 
	ONOTE VARCHAR2(100)
);

SELECT * FROM ORDERS