DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE PRODUCT;
--DROP TABLE PRODUCT CASCADE CONSTRAINTS;
CREATE TABLE PRODUCT
(
	PNO NUMBER PRIMARY KEY,
	PNAME VARCHAR2(200) NOT NULL,
	PIMAGE VARCHAR2(100),
	PLISTPRICE NUMBER NOT NULL,
	PPRICE NUMBER NOT NULL,
	PCATEGORY VARCHAR2(100),
	PTAG VARCHAR2(500),
	PDISRATE NUMBER,
	PDESC CLOB,
	PASDESC VARCHAR2(2000),
	PDETAIL VARCHAR2(2000),
	ANO NUMBER REFERENCES ARTIST (ANO),
	PREGDATE DATE
);







