DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE REVIEW;
CREATE TABLE REVIEW
(
	RNO NUMBER PRIMARY KEY,
	PNO NUMBER REFERENCES PRODUCT (PNO),
	MNO NUMBER REFERENCES MEMBER (MNO),
	RTITLE VARCHAR2(100) NOT NULL,
	RCONTENT VARCHAR2(4000),
	RFILENAME VARCHAR2(100),
	RRATING NUMBER,
	RREGDATE DATE
);

