DROP SEQUENCE STOCK_SEQ;
CREATE SEQUENCE STOCK_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE STOCK;
CREATE TABLE STOCK
(
	SNO NUMBER PRIMARY KEY, 
	PNO NUMBER REFERENCES PRODUCT (PNO), 
	OTITLE VARCHAR2(100),
	OCONTENT VARCHAR2(100),
	OADDPRICE NUMBER, 
	STOCK NUMBER
);