CREATE TABLE NATION(
    N_CODE NUMBER(3) NOT NULL PRIMARY KEY,
    N_NAME VARCHAR2(30) NOT NULL,
    N_PARTI_PERSON NUMBER DEFAULT 0,
    N_PARTI_EVENT NUMBER,
    N_PREV_RANK NUMBER,
    N_CURR_RANK NUMBER
);

CREATE TABLE EVENT(
    E_CODE NUMBER NOT NULL PRIMARY KEY,
    E_NAME VARCHAR2(30) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO VARCHAR2(100)
);

CREATE TABLE PLAYER(
    P_CODE NUMBER(3) NOT NULL PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    N_CODE NUMBER(3) REFERENCES NATION(N_CODE),
    E_CODE NUMBER REFERENCES EVENT(E_CODE),
    P_RANK NUMBER,
    P_AGE NUMBER(3)
);

CREATE TABLE SCHEDULE(
    N_CODE NUMBER(3) NOT NULL REFERENCES NATION(N_CODE),
    E_CODE NUMBER NOT NULL REFERENCES EVENT(E_CODE),
    S_START_DATE DATE,
    S_END_DATE DATE,
    S_INFO VARCHAR2(100),
    PRIMARY KEY(N_CODE, E_CODE)
);
