-- 직원(EMPLOYEE)
-- 부서(DEPARTMENT)

-- 1. 테이블 삭제 (FK먼저, PK 나중)
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

-- 2. 테이블 생성 (PK먼저, FK나중)
CREATE TABLE DEPARTMENT(
    DEPT_NO NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCATION VARCHAR2(15) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMP_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(15) NOT NULL,
    POSITION VARCHAR2(15),
    GENDER VARCHAR2(5),
    SALARY  NUMBER,
    HIRE_DATE DATE,
    DEPARTMENT NUMBER REFERENCES DEPARTMENT(DEPT_NO)
);

-- 3. DEPARTMENT 테이블에 ROW 삽입 (PK먼저 ROW삽입)
-- 부서번호: 1, 2, 3, 4
-- 부서명 : 영업부, 인사부, 총무부, 기획부
-- 위치 : 대구, 서울, 대구, 서울
INSERT INTO DEPARTMENT VALUES(1, '영업부', '대구');
INSERT INTO DEPARTMENT VALUES(2, '인사부', '서울');
INSERT INTO DEPARTMENT VALUES(3, '총무부', '대구');
INSERT INTO DEPARTMENT VALUES(4, '기획부', '서울');

-- 4. EMPLOYEE 테이블에 ROW 삽입 (FK나중 ROW삽입)
-- 전체 컬럼에 데이터(ROW)를 삽입하는 경우 삽입할 칼럼명을 생략한다.

INSERT INTO EMPLOYEE VALUES(1001, '구창민', '과장', 'M', 5000000, '95/05/01', 1);
INSERT INTO EMPLOYEE VALUES(1002, '김민서', '사원', 'M', 2500000, '17/09/01', 1);
INSERT INTO EMPLOYEE VALUES(1003, '이은영', '부장', 'F', 5500000, '90/09/01', 2);
INSERT INTO EMPLOYEE VALUES(1004, '한성일', '과장', 'M', 5000000, '93/04/01', 2);

-- 5. DEPARTMENT 테이블 ROW 수정
-- 총무부의 위치를 '부산'으로 수정하시오.
UPDATE DEPARTMENT SET LOCATION = '부산' WHERE DEOPT_NAME = '총무부';

--6. EMPLOYEE 테이블 ROW 수정
-- 1) POSITION이 '사원'인 직원들의 SALARY를 5% 인상하시오.
UPDATE EMPLOYEE SET SALARY = SALARY*1.05 WHERE POSITION = '사원';
-- 2) POSITION이 '과장'인 직원들의 POSITION을 '차장'으로 수정하고, SALARY를 10%인상하시오.
UPDATE EMPLOYEE SET POSITION = '차장', SALARY = SALARY * 1.1 WHERE POSITION = '과장';

-- 7. DEPARTMENT 테이블 ROW 삭제
-- 1) '기획부'를 삭제하시오.
DELETE FROM DEPARTMENT WHERE DEPT_NAME = '기획부';

