DROP TABLE CUSTOMER;
DROP TABLE BANK;
CREATE TABLE BANK(
	BANK_CODE VARCHAR2(20),
	BANK_NAME VARCHAR2(20),
	PRIMARY KEY(BANK_CODE)
);

CREATE TABLE CUSTOMER(
	NO NUMBER,
	NAME VARCHAR2(30) NOT NULL,
	PHONE VARCHAR2(30) UNIQUE,
	AGE NUMBER CHECK(AGE >= 0 AND AGE <= 100),
	-- AGE NUMBER CHECK(AGE BETWEEN 0 AND 100),
	BANK_CODE VARCHAR2(20),
	PRIMARY KEY(NO),
	FOREIGN KEY(BANK_CODE) REFERENCES BANK(BANK_CODE)
);