DROP SEQUENCE CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE CONTACT;
CREATE TABLE CONTACT
(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(100),
	PHONE VARCHAR2(50),
	ADDRESS VARCHAR2(200),
	EMAIL VARCHAR2(100),
	NOTE VARCHAR2(1000)
);

INSERT INTO CONTACT values(CONTACT_SEQ.NEXTVAL, '제임스', '010-0000-0000', '서울시 마포구', 'james@app.com', '친구');