DROP SEQUENCE USERS_SEQ;
CREATE SEQUENCE USERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE USERS;
CREATE TABLE USERS
(
	NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(50),
	PHONE VARCHAR2(50)
);