DROP SEQUENCE SIMPLE_SEQ2;
CREATE SEQUENCE SIMPLE_SEQ2
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE SIMPLE2;
CREATE TABLE SIMPLE2
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100),
	TITLE VARCHAR2(1000),
	CONTENT VARCHAR2(4000),
	REGDATE DATE
);

