DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100),
	TITLE VARCHAR2(1000),
	CONTENT VARCHAR2(4000),
	FILENAME VARCHAR2(300),
	REGDATE DATE
);